version: "3.2"

services:
  rabbitmq:
    container_name: rabbit1
    hostname: rabbit1.vnet
    build:
      dockerfile: Dockerfile
      context: ./
    image: rabbitmq:3.5.3-management
    ports:
      - 5672:5672
      - 15672:15672